version: '2'

services:

    crab1:
        container_name: crab1
        command: /.env/bin/apistar run
#        command: ls -la
        ports:
            - "8080:80"
        build:
            context: ./
        restart: on-failure:1
        network_mode: "bridge"
        logging:
            driver: "json-file"
        tty: true
        stdin_open: true
