version: '2'

services:

    crab1:
        container_name: crab1
        command: /app_root/.env/bin/python3
        ports:
            - "80:80"
            - "443:443"
        build:
            context: ./
        restart: on-failure:1
        network_mode: "bridge"
        logging:
            driver: "json-file"
        tty: true
        stdin_open: true
